### ISSUE TITLE
生成中提示「辨識項目的其中之一使用無效的格式」

### ISSUE THREAD

**Issue by maplestyle** [OpenMLTD/MLTDTools#4] opened 2018-09-15 01:51 UTC
![20180915095046](https://user-images.githubusercontent.com/41418628/45581222-ed5e0080-b8cc-11e8-9aaa-fa42a92bf3c6.png)

**Comment by hozuki** [comment] 2018-09-15 02:58
Can you attach the files please?

**Comment by hozuki** [comment] 2018-09-15 03:34
OK I found the problem.

The files you used are:

```plain
2018-09-14  17:31            25,512 cam_hzwend.imo.unity3d
2018-09-14  17:33           341,031 cb_pr001_015siz.unity3d
2018-09-14  17:32             1,160 ch_sr104_015siz.unity3d
2018-09-14  17:47         3,276,255 dan_hzwend_01.imo.unity3d
2018-09-14  17:30            82,762 scrobj_hzwend.unity3d
```

(`cb_ex002_a` is filtered out because I didn't write a name filter for it. I'll fix this later.)

Notice that the size of `ch_sr104_015siz` is only ~1 KB. This means this file is not the correct one.
Actually, it is a texture override bundle, replacing the corresponding textures in `ch_sr004_015siz` (size: 415.2 KB). So you should use `ch_sr004_015siz` for the model input, then extract its textures, and replace the textures with those in `ch_sr104_015siz`. Now the model will be textured as its variant (アナザー衣装).

**Comment by maplestyle** [comment] 2018-09-15 04:09
更換ch_sr004_015siz後還是一樣報錯><
[ch_sr004_015siz.zip](https://github.com/OpenMLTD/MLTDTools/files/2385350/ch_sr004_015siz.zip)

**Comment by hozuki** [comment] 2018-09-15 05:05
It turned out that `cb_pr001_015siz` has two asset file entries, one of which is a dummy, while the other bundles (e.g. ss001) have only one entry. The problem is now fixed.

**Comment by maplestyle** [comment] 2018-09-15 05:37
it works. thank you so much

**Closed** 2018-09-15 11:13 UTC
